server:
  port: 9090
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: hkmy
    password: 5JwVKUqkNoTjBYQF_E43gbjT4
    url: jdbc:mysql://10.228.5.14:3306/hkshow?characterEncoding=utf8
  mail:
    host: smtp.163.com
    username: shshj0321@163.com #发送人的用户名（From）
    password: KCTQJWXRBZRLPQXA
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    ##         ssl:
    ##           enable :true
    default-encoding: utf-8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
